[feat] vendor profiles integration
CogburnWire/saleor-dashboard pull request #15
Opened 2021-10-25 11:41 UTC by ajmiclat

I want to merge this change because...

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Translated strings are extracted.
1. [ ] Number of API calls is optimized.
1. [ ] The changes are tested.
1. [ ] Data-test are added for new elements.
1. [ ] Type definitions are up to date.
1. [ ] Changes are mentioned in the changelog.
1. [ ] The changes are tested in different browsers (Chrome, Firefox, Safari).
1. [ ] The changes are tested in light and dark mode.

### Test environment config

API_URI=https://master.staging.saleor.cloud/graphql/

2021-10-26 19:28 UTC, jsnbuchanan requested changes

2021-10-26 19:28 UTC, jsnbuchanan commented on schema.graphql
> +  errors: [Error!]! @deprecated(reason: "Use typed errors with error codes. This field will be removed after 2020-07-31.")
@ajmiclat question about this `@deprecated` reason. The message states the field will be removed after `2020-07-31`. Is that correct? Or should we be doing something else here? Same question for the other places that resemble this.

2021-10-26 19:28 UTC, jsnbuchanan commented on src/extensions/Vendors/mutations.ts
> +export interface VendorInput {
@ajmiclat should this interface include a list of image URLs?

2021-10-26 19:28 UTC, jsnbuchanan commented on src/extensions/Vendors/types/Vendor.ts
> +export interface Vendor {
Seems like we're duplicating a lot of interfaces. Does the API change between `create / update` enough to warrant separate interface definitions? or should we use a single interface across the API?

Seems like a lot of duplicate boilerplate interface code. I may be wrong, but wanted to ask the question.

2021-10-26 19:28 UTC, jsnbuchanan commented on src/types/globalTypes.ts
> +
This seems like another duplicate. I haven't called out all the places, just wanted to call out a few.

2021-10-29 10:15 UTC, ajmiclat commented on src/extensions/Vendors/mutations.ts
> +export interface VendorInput {
@jsnbuchanan the image upload has a separate mutation.
https://github.com/CogburnWire/saleor-dashboard/pull/15/files#diff-efc1675187620595b0844197a25c35eac9b6df752f9182e5cffddee6f27a8489R5514-R5517

2021-10-29 10:16 UTC, ajmiclat commented on schema.graphql
> +  errors: [Error!]! @deprecated(reason: "Use typed errors with error codes. This field will be removed after 2020-07-31.")
@jsnbuchanan this is auto generated. we'll handle the error codes in the API side since the schema is generated there. 😄

2021-10-29 10:20 UTC, ajmiclat commented on src/extensions/Vendors/types/Vendor.ts
> +export interface Vendor {
@jsnbuchanan yea that's what I notice as well. currently these types are auto generated by a script and are specific per query/mutation. when you check for example the types, it has like `Vendor`, `VendorCreate`, `VendorUpdate`, etc.

2021-10-29 13:54 UTC, garguelles approved these changes

2021-10-29 13:55 UTC, ajmiclat commented
@jsnbuchanan will do an initial merge for now. will address the types errors in the API.

2021-10-29 13:56 UTC, merged